// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHInhzBLQMX8lSpd7r7gXo761h_vGTXSI',
    appId: '1:30627435273:web:5a92266bb15ea381ccb9d8',
    messagingSenderId: '30627435273',
    projectId: 'famers-market-b9b62',
    authDomain: 'famers-market-b9b62.firebaseapp.com',
    storageBucket: 'famers-market-b9b62.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNCqYRUtP4p8_UYLDMLXTp2PZ9sY0z450',
    appId: '1:30627435273:android:e56cd0d2ccaf39edccb9d8',
    messagingSenderId: '30627435273',
    projectId: 'famers-market-b9b62',
    storageBucket: 'famers-market-b9b62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI8S_kaJGOSj56Gdpgo_J-H-0v8IwV2UM',
    appId: '1:30627435273:ios:49b5878c6bd43c3cccb9d8',
    messagingSenderId: '30627435273',
    projectId: 'famers-market-b9b62',
    storageBucket: 'famers-market-b9b62.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI8S_kaJGOSj56Gdpgo_J-H-0v8IwV2UM',
    appId: '1:30627435273:ios:49b5878c6bd43c3cccb9d8',
    messagingSenderId: '30627435273',
    projectId: 'famers-market-b9b62',
    storageBucket: 'famers-market-b9b62.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHInhzBLQMX8lSpd7r7gXo761h_vGTXSI',
    appId: '1:30627435273:web:80d88245d0139f21ccb9d8',
    messagingSenderId: '30627435273',
    projectId: 'famers-market-b9b62',
    authDomain: 'famers-market-b9b62.firebaseapp.com',
    storageBucket: 'famers-market-b9b62.firebasestorage.app',
  );
}
